### ISSUE TITLE
EWAHCompressedBitMap: You can only reduce the size of the bitmap within the scope of the last word.

### ISSUE THREAD

**Issue by svanmald** [lemire/javaewah#73]
Example:

```java
EWAHCompressedBitmap main = new EWAHCompressedBitmap();
EWAHCompressedBitmap other = new EWAHCompressedBitmap();
main.clear(10684);
other = other.andNot(main);
other = other.or(main);
new EWAHCompressedBitmap().or(other);
```

Output
```
You can only reduce the size of the bitmap within the scope of the last word. To extend the bitmap, please call setSizeInBits(int,boolean).
java.lang.RuntimeException: You can only reduce the size of the bitmap within the scope of the last word. To extend the bitmap, please call setSizeInBits(int,boolean).
	at com.googlecode.javaewah.EWAHCompressedBitmap.setSizeInBitsWithinLastWord(EWAHCompressedBitmap.java:1424)
	at com.googlecode.javaewah.EWAHCompressedBitmap.orToContainer(EWAHCompressedBitmap.java:1084)
	at com.googlecode.javaewah.EWAHCompressedBitmap.or(EWAHCompressedBitmap.java:1020)
```

**Comment by lemire** [comment]
Bug created by my bad fix of issue 70.
